environments:
  benrd:
  bingrd:
  dev:
  prod-blue:
  prod-green:
  prototype:


releases:

  - name: eicallbackapi-{{ requiredEnv "BRANCH" }}
    chart: ../helm/charts/ei-callback-bot
    namespace: ei-callback-{{ requiredEnv "BRANCH" }}
    values:
      - overrides/ei-callback-bot-api.yaml.gotmpl
    labels:
        category: prototype
        app: ei-callback-bot
        tier: api
    wait: false
    installed: true
    force: false