repositories:
    - name: dts
      url: https://helm.dts-stn.com
{{- if or (eq .Environment.Name "prod-blue") (eq .Environment.Name "prod-green") }}
context: EsDCDTSRG-K8S
{{ else }}
context: EsDCDTSDevRG-K8S
{{ end }}

environments:
    dev:
    prod-blue:
    prod-green:

releases:
# Question Priority Service
  - name: oas-callback-bot-{{ .Environment.Name }}
    chart: ../helm/charts/oas-callback-bot
    version: 0.0.1
    values:
      - overrides/callback.yaml.gotmpl
    labels:
        category: dts
        app: oas-callback-bot
        tier: server
    namespace: oas-callback-bot-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false