apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{ with .Values.deployment.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ if .Values.secrets.enabled }}
      initContainers:
        - name: init-secrets
          image: {{ .Values.secrets.image }}
          imagePullPolicy: Always
          {{- if .Values.secrets.env }}
          env:
{{ toYaml .Values.secrets.env | indent 10 }}
          {{ end }}     
{{ end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: LuisAppIdFR
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: LuisAppIdFR
          - name: LuisAPIKeyFR
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: LuisAPIKeyFR
          - name: LuisAPIHostNameFR
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: LuisAPIHostNameFR
          - name: LuisAppIdEN
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: LuisAppIdEN
          - name: LuisAPIKeyEN
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: LuisAPIKeyEN
          - name: LuisAPIHostNameEN
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: LuisAPIHostNameEN
          - name: MicrosoftAppId
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: MicrosoftAppId
          - name: MicrosoftAppPassword
            valueFrom:
              secretKeyRef:
                name: {{ include "fullname" . }}
                key: MicrosoftAppPassword
{{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 10 }}
{{- end }}
          ports:
            - name: http
              {{ if .Values.port }}
              containerPort: {{ .Values.port }}
              {{ else }}
              containerPort: 3000
              {{ end }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessPath }}
              port: http
            initialDelaySeconds: {{ .Values.livenessDelay }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessPath }}
              port: http
            initialDelaySeconds: {{ .Values.readinessDelay }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

