{{ if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: Group
  name: {{ .Values.rbac.groupId }} # Name is case sensitiv
  namespace: {{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.clusterRoleName }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}