name: Build and Push Image To MS ACR

on:
  pull_request:
    branches: [main]

jobs:
  build_publish:
    name: Build and push dev container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2
      - name: "Generate Build Number"
        uses: einaregilsson/build-number@v1
        with:
          token: ${{ secrets.DTSROBOT_API_TOKEN }}
      - name: Print new build number
        run: echo Build number is $BUILD_NUMBER

      - name: Login to Azure Cloud
        uses: azure/docker-login@v1
        with:
          login-server: mtscontainers.azurecr.io
          username: ${{ secrets.AZURE_GITHUB_SPN_ID }}
          password: ${{ secrets.AZURE_GITHUB_SPN_PASS }}



      - name: Docker Build and Push Images to Azure Repo
        run: |
          docker build -t mtscontainers.azurecr.io/dts-oas-callback-bot:latest .
          docker tag mtscontainers.azurecr.io/dts-oas-callback-bot:latest mtscontainers.azurecr.io/dts-oas-callback-bot:$BUILD_NUMBER
          docker push mtscontainers.azurecr.io/dts-oas-callback-bot:latest
          docker push mtscontainers.azurecr.io/dts-oas-callback-bot:$BUILD_NUMBER
  # logout after build successful
      - name: Azure logout
        run: |
          az logout
