name: Build and Push Image To MS ACR

on:
  pull_request:
    branches: [main]

jobs:
  build_publish:
    name: Build and push dev container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v2

      - name: Docker Build and Push Images to Azure Repo
        run: |
          az login --service-principal -u ${{ secrets.AZURE_GITHUB_SPN_ID }} -p ${{ secrets.AZURE_GITHUB_SPN_PASS }} -t ${{ secrets.AZURE_TENANT_ID }}
          az acr login --name mtscontainers
          docker build -f Dockerfile.dev -t mtscontainers.azurecr.io/dts-oas-callback-bot:latest .
          docker tag mtscontainers.azurecr.io/dts-oas-callback-bot:latest mtscontainers.azurecr.io/dts-oas-callback-bot: $GITHUB_RUN_NUMBER
          docker push mtscontainers.azurecr.io/dts-oas-callback-bot:latest
          docker push mtscontainers.azurecr.io/dts-oas-callback-bot:$GITHUB_RUN_NUMBER
        env: 
          GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER
  # logout after build successful
      - name: Azure logout
        run: |
          az logout
